### ISSUE TITLE
2.x Guzzle PEM File out of date

### ISSUE THREAD

**Issue by funkflute** [thephpleague/omnipay#518] opened 2018-07-27 17:26 UTC
The version of Guzzle required for 2.x has an out of date PEM file, so my SSL connections to our CC proc. started failing... (curl error 60)... other than upgrading to omnipay 3.x, is there a fix for this, or a way to get omnipay to get guzzle to use a different cainfo cert?

I have tried updating `curl.cainfo` in my `php.ini` to no effect, and looks like Guzzle 3 can only change the PEM programmatically (ClientInterface::setSslVerification), not through system settings.

**Comment by barryvdh** [comment] 2018-07-29 07:05
Closing as duplicate of https://github.com/thephpleague/omnipay-common/issues/193

**Closed by barryvdh** 2018-07-29 07:05 UTC
